
version: "3.2"
services:
  shiny:
    # build shiny image
    build: ./shiny

    volumes:
      - type: bind
        source: ./shiny-apps
        target: /srv/shiny-server/

      - type: volume
        source: shiny-logs
        target: /var/log/shiny-server/

      - type: bind
        source: ./shiny/shiny-server.conf
        target: /etc/shiny-server/shiny-server.conf

    # expose the shiny server ports
    expose:
      - "3838"

    depends_on:
      - db

    links:
      - db

    # auto restart container
    restart: always

  nginx:
    image: "nginx:1.17"

    ports:
      - "22080:80"

    links:
      - shiny

    volumes:
      - type: bind
        source: ./nginx-conf.d/
        target: /etc/nginx/conf.d/

    # auto restart container
    restart: always

  db:
    image: postgres:10.12

    env_file:
      - .env

    volumes:
    - type: volume
      source: db-data
      target: /var/lib/postgresql/data

networks:
  default:

volumes:
  shiny-logs:
  db-data:
