
version: "3.2"
services:
  shiny:
    # build shiny image
    build: ./shiny

    volumes:
      - type: bind
        source: ./shiny-apps
        target: /srv/shiny-server/

      - type: volume
        source: shiny-logs
        target: /var/log/shiny-server/

      - type: bind
        source: ./shiny/shiny-server.conf
        target: /etc/shiny-server/shiny-server.conf

    # expose the shiny server ports
    expose:
      - "3838"

    # auto restart container
    restart: always

  nginx:
    image: "nginx:1.17"

    ports:
      - "22080:80"

    links:
      - shiny:shiny

    volumes:
      - type: bind
        source: ./nginx-conf.d/
        target: /etc/nginx/conf.d/

    # auto restart container
    restart: always

networks:
  default:

volumes:
  shiny-logs:
