
services:
  shiny-4.5:
    # get image from dockerhub
    image: bunop/shiny-server_shiny:4.5.1

    volumes:
      - type: bind
        source: ./shiny-apps
        target: /srv/shiny-server/

      - type: volume
        source: shiny-4.5-logs
        target: /var/log/shiny-server/

      - type: volume
        source: renv-cache
        target: /srv/renv-cache

      - type: bind
        source: ./shiny/shiny-server.conf
        target: /etc/shiny-server/shiny-server.conf

    # expose the shiny server ports
    expose:
      - "3838"

    # auto restart container
    restart: always

  shiny-4.0:
    # get image from dockerhub
    image: bunop/shiny-server_shiny:4.0.5

    volumes:
      - type: bind
        source: ./shiny-apps
        target: /srv/shiny-server/

      - type: volume
        source: shiny-4.0-logs
        target: /var/log/shiny-server/

      - type: volume
        source: renv-cache
        target: /srv/renv-cache

      - type: bind
        source: ./shiny/shiny-server.conf
        target: /etc/shiny-server/shiny-server.conf

    # expose the shiny server ports
    expose:
      - "3838"

    # auto restart container
    restart: always

  db:
    # get the latest mysql server
    image: mariadb:10.5

    # Set db environment
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SHINY_DATABASE: ${SHINY_DATABASE}
      SHINY_USER: ${SHINY_USER}
      SHINY_PASSWORD: ${SHINY_PASSWORD}

    # to export volume, as recommeded in https://registry.hub.docker.com/u/library/mysql/
    volumes:
      - type: bind
        source: ./mysql-data/
        target: /var/lib/mysql

      - type: bind
        source: ./docker-entrypoint-initdb.d/
        target: /docker-entrypoint-initdb.d

  uwsgi:
    # get image from dockerhub
    image: bunop/shiny-server_uwsgi:2.2

    # You can pass multiple environment variables from an external file through
    # to a service’s containers with the ‘env_file’ option
    env_file:
      - .env

    # exec a different command from image
    command: uwsgi --ini /var/uwsgi/shiny_uwsgi.ini --memory-report

    # set working dir for uwsgi
    working_dir: /var/uwsgi/shiny/

    # define volumes
    volumes:
      - type: bind
        source: ./django-data/
        target: /var/uwsgi/

    # Expose the default port

    # link container to database
    links:
      - db

  nginx:
    image: "nginx:1.29"

    ports:
      - "22080:80"

    links:
      - shiny-4.5
      - shiny-4.0
      - uwsgi

    volumes:
      - type: bind
        source: ./nginx-conf.d/
        target: /etc/nginx/conf.d/

      - type: bind
        source: ./django-data/
        target: /var/uwsgi/

    # auto restart container
    restart: always

networks:
  default:

volumes:
  shiny-4.0-logs:
  shiny-4.5-logs:
  renv-cache:
