
version: "3.2"
services:
  shiny:
    # build shiny image
    build: ./shiny

    volumes:
      - type: bind
        source: ./shiny-apps
        target: /srv/shiny-server/

      - type: volume
        source: shiny-logs
        target: /var/log/shiny-server/

      - type: bind
        source: ./shiny/shiny-server.conf
        target: /etc/shiny-server/shiny-server.conf

    # expose the shiny server ports
    expose:
      - "3838"

    # auto restart container
    restart: always

  db:
    # get the latest mysql server
    image: mariadb:10.5

    # Set db environment
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SHINY_DATABASE: ${SHINY_DATABASE}
      SHINY_USER: ${SHINY_USER}
      SHINY_PASSWORD: ${SHINY_PASSWORD}

    # to export volume, as recommeded in https://registry.hub.docker.com/u/library/mysql/
    volumes:
      - type: bind
        source: ./mysql-data/
        target: /var/lib/mysql

      - type: bind
        source: ./docker-entrypoint-initdb.d/
        target: /docker-entrypoint-initdb.d

  nginx:
    image: "nginx:1.17"

    ports:
      - "22080:80"

    links:
      - shiny:shiny

    volumes:
      - type: bind
        source: ./nginx-conf.d/
        target: /etc/nginx/conf.d/

    # auto restart container
    restart: always

networks:
  default:

volumes:
  shiny-logs:
