# Generated by Django 2.2.16 on 2020-10-12 16:25

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0003_shinyapp_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shinyapp',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, default=''),
        ),
    ]
