# Generated by Django 3.2.25 on 2025-10-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0004_auto_20201012_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shinyapp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
