# Generated by Django 5.2.7 on 2025-10-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serve", "0005_alter_shinyapp_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="shinyapp",
            name="r_version",
            field=models.CharField(
                choices=[("4.0", "R 4.0"), ("4.5", "R 4.5")],
                default="4.5",
                max_length=3,
                verbose_name="R Version",
            ),
        ),
    ]
