# Generated by Django 5.2.7 on 2025-10-29

from django.db import migrations


def add_wordcloud_app(apps, schema_editor):
    """Add WordCloud application"""
    ShinyApp = apps.get_model('serve', 'ShinyApp')

    # Create WordCloud app
    ShinyApp.objects.create(
        location='/shiny-4.5/082-word-cloud/',
        title='WordCloud',
        slug='wordcloud',
        description='A Shiny application that generates word clouds from text input',
        is_public=False,
        r_version='4.5',
        thumbnail='default.png'
    )


def remove_wordcloud_app(apps, schema_editor):
    """Remove WordCloud application"""
    ShinyApp = apps.get_model('serve', 'ShinyApp')
    ShinyApp.objects.filter(slug='wordcloud').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0007_add_hello_shiny_app'),
    ]

    operations = [
        migrations.RunPython(add_wordcloud_app, remove_wordcloud_app),
    ]
